apiVersion: apps/v1
kind: Deployment
metadata:
  name: miapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miapp
  template:
    metadata:
      labels:
        app: miapp
    spec:
      containers:
        - name: miapp
          image: usuario/miapp:1.0
          ports:
            - containerPort: 8080
